version: "3.7"
services:
  mongodb:
    image: mongo
    restart: always
    container_name: sample-mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
      - MONGO_INITDB_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - ./docker/mongo/initdb.d/:/docker-entrypoint-initdb.d/:ro
  mongo-express:
    image: mongo-express
    restart: always
    container_name: sample-mongo-express
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
  app:
    build: ./docker/app
    container_name: sample-app
    ports:
      - 8081:8080
    environment:
      - SPRING_DATA_MONGODB_USERNAME=${MONGODB_USERNAME}
      - SPRING_DATA_MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - SPRING_DATA_MONGODB_HOST=${MONGODB_HOST}
      - SPRING_DATA_MONGODB_PORT=${MONGODB_PORT}
      - SPRING_DATA_MONGODB_DATABASE=${MONGODB_DATABASE}
    depends_on:
      - mongo-express
